import placeholder_image_svg from "../../assets/images/test_image.svg";

export const testItems = [
  {
    name: "Базова футболка",
    description: "Бавовняна базова футболка прямого крою",
    price: 799,
    discount: 0,
    availability: "In stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
    image: placeholder_image_svg,
  },
  {
    name: "Оверсайз (oversize) футболка",
    description: "Футболка вільного крою з щільної бавовни",
    price: 999,
    discount: 10,
    availability: "In stock",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Grey"],
    image: placeholder_image_svg,
  },
  {
    name: "Класичне худі",
    description: "Тепле худі з капюшоном та кишенею кенгуру",
    price: 1899,
    discount: 15,
    availability: "In stock",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Beige"],
    image: placeholder_image_svg,
  },
  {
    name: "Світшот есеншіал (essential)",
    description: "Мінімалістичний світшот із м'якої бавовни",
    price: 1499,
    discount: 0,
    availability: "Preorder",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Navy"],
    image: placeholder_image_svg,
  },
  {
    name: "Прямі джинси",
    description: "Класичні джинси прямого крою",
    price: 2199,
    discount: 20,
    availability: "In stock",
    sizes: ["S", "M", "L"],
    colors: ["Blue", "Black"],
    image: placeholder_image_svg,
  },
  {
    name: "Карго (cargo) шорти",
    description: "Шорти вільного крою з бічними кишенями",
    price: 1299,
    discount: 10,
    availability: "In stock",
    sizes: ["M", "L", "XL"],
    colors: ["Khaki", "Black"],
    image: placeholder_image_svg,
  },
  {
    name: "Карго (cargo) штани",
    description: "Вільні штани з накладними кишенями",
    price: 1999,
    discount: 0,
    availability: "In stock",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Khaki"],
    image: placeholder_image_svg,
  },
  {
    name: "Спортивні штани",
    description: "М'які спортивні штани з еластичним поясом",
    price: 1399,
    discount: 10,
    availability: "Out of stock",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Grey"],
    image: placeholder_image_svg,
  },
  {
    name: "Джинсова куртка",
    description: "Класична джинсова куртка прямого силуету",
    price: 2899,
    discount: 0,
    availability: "In stock",
    sizes: ["M", "L", "XL"],
    colors: ["Blue"],
    image: placeholder_image_svg,
  },
  {
    name: "Бомбер (bomber) куртка",
    description: "Легка демісезонна куртка-бомбер",
    price: 3199,
    discount: 15,
    availability: "Preorder",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Olive"],
    image: placeholder_image_svg,
  },
  {
    name: "Пухова жилетка",
    description: "Легка утеплена жилетка на блискавці",
    price: 2499,
    discount: 0,
    availability: "In stock",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Navy"],
    image: placeholder_image_svg,
  },
  {
    name: "Класична сорочка",
    description: "Бавовняна сорочка класичного крою",
    price: 1599,
    discount: 0,
    availability: "In stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Blue"],
    image: placeholder_image_svg,
  },
  {
    name: "Лляна сорочка",
    description: "Легка сорочка з натурального льону",
    price: 1799,
    discount: 10,
    availability: "In stock",
    sizes: ["S", "M", "L"],
    colors: ["White", "Beige"],
    image: placeholder_image_svg,
  },
  {
    name: "Поло класичний (classic)",
    description: "Класична футболка-поло з коміром",
    price: 1199,
    discount: 0,
    availability: "In stock",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "White", "Navy"],
    image: placeholder_image_svg,
  },
  {
    name: "Трикотажний светр",
    description: "М'який светр базового прямого крою",
    price: 1999,
    discount: 20,
    availability: "In stock",
    sizes: ["S", "M", "L"],
    colors: ["Beige", "Grey"],
    image: placeholder_image_svg,
  },
  {
    name: "Шорти Basic",
    description: "Бавовняні повсякденні шорти",
    price: 999,
    discount: 0,
    availability: "Out of stock",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey"],
    image: placeholder_image_svg,
  },
];
